var quotes = [
  'Jika pasanganmu meminta kamu meninggalkan karirmu, Apa yang akan kamu lakukan?',
  'Kalau hari ini adalah hari terakhir kita bersama, apa yang ingin kamu sampaikan?',
  'Kalau diberi kesempatan memulai dari awal, hal apa yang ingin kamu ubah dari hubungan kita?',
  'Apakah kamu pikir kita akan menjadi orang tua yang baik kelak?',
  'Nilai apa yang ingin kamu terapkan ke anak anak kita nanti?',
  'Apakah kamu punya rencana memperkerjakan asisten rumah tangga atau pengasuh? Berapa dan Mengapa?',
  'Bagaimana kesan pertama teman teman dan keluargamu tentang pasanganmu? Bagaimana pandangan mereka sekarang?',
  'Akan tinggal di mana setelah menikah? Apakah setuju jika tinggal bersama orang tua atau mertua?',
  'Seberapa sering akan mengunjungi orang tua atau mertua?',
  'Kalau tiba-tiba kamu harus LDR dengan pasanganmu, Bagaimana?',
  'Adakah yang kurang kamu sukai dari orang tua atau mertua?',
  'Apakah boleh memberi uang bulanan kepada orang tua atau mertua? Berapa besarannya?',
  'Apakah boleh memberikan bantuan dana kepada saudara atau anggota keluarga yang sedang membutuhkan? ',
  'Bolehkah membiayai pendidikan saudara atau anggota keluarga?',
  'Bagaimana pendapatmu mengenai KDRT? Bagaimana jika pasangan melakukan KDRT?',
  'Bagaimana pandanganmu mengenai poligami?',
  'Apakah pasanganmu boleh Me Time bersama teman-temannya? ',
  'Bagaimana pandanganmu tentang traveling bersama anak/baby?',
  'Bolehkah punya hewan peliharaan di rumah? Bagaimana jika itu permintaan anak?',
  'Bolehkah pasanganmu mempunyai sahabat akrab lawan jenis?',
  'Bagaimana kamu membagi tugas-tugas rumah tangga?',
  'Bagaimana pandanganmu mengenai pendidikan anak kelak? Apakah harus sekolah swasta atau sekolah negeri?',
  'Jika harus meninggalkan anak, pada siapa anak akan dititipkan? baby sitter, daycare, atau ke orang tua atau mertua? Mengapa?',
  'Apakah setuju jika anak diurus orang tua atau mertua?',
  'Apakah boleh jika child free atau tidak memiliki anak? Mengapa?',
  'Kapan ingin memiliki anak? Ingin punya anak berapa dan jangka waktu berapa lama?',
  'Jika tidak bisa memiliki anak, apakah kamu akan menikah lagi? Bagaimana solusimu?',
  'Jika tidak bisa memiliki anak, Bagaimana pandanganmu mengenai adopsi? Mengapa?',
  'Jika tidak bisa memiliki anak, Bagaimana pandanganmu mengenai bayi tabung / IVF? Mengapa?',
  'Apakah nantinya akan ber-KB? Jika iya, metode apa yang digunakan? Mengapa?',
  'Apakah istri tetap boleh bekerja? Bolehkan istri tetap bekerja setelah memiliki anak?',
  'Bagaimana pendapatmu mengenai investasi untuk dana pendidikan anak? Jika iya, jenis investasi apa?',
  'Bagaimana caramu mengatur dana darurat kita kelak? Berapa besaran dana darurat yang harus disiapkan?',
  'Apakah kamu baik-baik saja dengan berhutang atau kamu ingin hidup bebas hutang? Jelaskan',
  'Apakah kamu lebih suka memiliki tabungan masing-masing atau membuat tabungan bersama kelak?',
  'Siapa yang memegang kendali uang? Apakah semua gaji suami diberikan ke istri atau hanya uang belanja saja?',
  'Apakah boleh berbelanja tanpa izin pasangan?',
  'Bagaimana jika penghasilan istri lebih besar?',
  'Apa alasan kamu yakin dan ingin menikah dengan pasanganmu sekarang?',
  'Deskripsikan rencana kehidupan pernikahan yang kamu impikan.',
  'Menurutmu, bagaimana batas privasi kita setelah menikah kelak? Apakah akan berubah atau tetap sama?',
  'Kalau suatu hari orang tua kamu dan pasanganmu hampir tenggelam di laut, yang mana yang kamu selamatkan?',
  'Bagaimana pandanganmu soal kelahiran? Apakah harus normal atau tidak apa apa jika harus Operasi caesar?',
  'Bagaimana pendapatmu jika orang tua atau mertua terlalu ikut campur urusan rumah tangga kita kelak? Apa yang akan kamu lakukan?',
  'Berapa kali minimal dan maksimal kamu ingin berhubungan seks dalam seminggu?',
  'Apakah kita akan memiliki anggaran setiap bulan?',
  'Berapa banyak yang akan kamu belanjakan untuk belanjaan dalam seminggu atau bulan?',
  'Seberapa sering kamu berharap untuk makan di luar setiap minggu?',
  'Aturan macam apa yang ingin kamu buat untuk pernikahan kita?',
  'Apakah karier yang hebat lebih penting daripada pernikahan dan keluarga kita?',
  'Bagaimana keluargamu menyelesaikan konflik ketika kamu tumbuh dewasa? ',
  'Maukah kamu pergi ke konseling pernikahan / Psikolog jika pasanganmu memintanya?',
  'Apakah kamu atau orang tuamu memiliki hutang? Jelaskan',
  'Apa kamu atau orang tuamu memiliki alergi atau penyakit genetik?',
  'Di lingkungan seperti apakah kamu ingin membesarkan anak?',
  'Apa yang akan kamu lakukan jika ada hal yang tidak sesuai rencana keuangan?',
  'Apakah kamu memiliki rencana tertentu untuk pendidikan dan profesi anakmu nanti?',
  'Apakah menurutmu menonton pornografi adalah bentuk perselingkuhan? Kenapa?',
  'Apakah menurutmu setelah menikah nanti kita perlu terbuka membicarakan tentang kehidupan seks kita, seperti apa yang kita suka dan tidak suka? Kenapa?',
  'Apakah menurutmu perlu merayakan ultah, anniversary, dan perayaan hari jadi lainnya?',
  'Berapa maksimal biaya menikah yang akan atau mau dikeluarkan?',
  'Deskripsikan konsep wedding yang kamu inginkan',
  'Bagaimana pandanganmu mengenai asuransi? Apakah setelah menikah dan memiliki anak perlu asuransi? Asuransi apa saja?',
  'Apakah boleh jika pasangan mau kuliah lagi? Jika boleh, apakah harus pakai uang sendiri, dibiayai suami, atau bagaimana? Lalu bagaimana dengan anak?',
];

function newQuote() {
  var randomNumber = Math.floor(Math.random() * quotes.length);
  document.getElementById('quote').innerHTML = quotes[randomNumber];
}

newQuote();
