var quotes = [
  'Menurut kamu, apa alasan kita masih bertahan selama ini?',
  'Kejadian apa yang selalu terkenang di ingatanmu tentang kita?',
  'Bagaimana kamu menjelaskan hubungan kita kepada orang yang tidak kamu kenal?',
  'Apa momen paling memalukan yang kita alami bersama?',
  'Apa hal yang selalu ingin kamu ungkapkan kepada pasanganmu namun belum bisa kamu ungkapkan?',
  'Jika kelak kamu tidak bersama pasanganmu, apa yang akan kamu lakukan?',
  'Apa yang menurutmu bisa kita lakukan untuk memperkuat hubungan kita?',
  'Apa kamu pernah merasa tidak nyaman bercerita ke pasanganmu tentang suatu hal? Mengapa?',
  'Jika hubungan kita berakhir, apa harapanmu untukku?',
  'Menurutmu, apa yang harus kita perbaiki dalam hubungan ini?',
  'Adakah topik yang selalu jadi pertengkaran diantara kita? Apa solusinya?',
  'Sebutkan hal yang paling romantis yang pernah dilakukan pasanganmu untukmu? Jelaskan?',
  'Apakah virginitas pasangan menjadi salah satu faktor pertimbanganmu?',
  'Apa yang kamu lakukan jika orang tuamu tidak menyukai pasanganmu?',
  'Apakah kamu memperlakukan pasanganmu berbeda dengan teman – teman lain? Jelaskan?',
  'Sebutkan kesan pertamamu tentang pasanganmu?',
  'Menurutmu, apa yang membuat kita cocok satu sama lain?',
  'Apa yang paling kamu syukuri dari hubungan kita?',
  'Adakah tujuan bersama yang ingin kamu capai bersama pasangan? Ceritakan',
  'Pernahkah kamu berdoa kepada Tuhan untuk hubungan kita? Apakah itu?',
  'Jika aku/kamu hamil diluar nikah, apa yang akan kamu lakukan?',
  'Pernahkah kamu merasa kesepian dalam hubungan ini? Jelaskan?',
  'Jika mantan pasangan mu menghubungi mu pukul 12 malam, apakah kamu akan menjawab atau memberitahuku terlebih dahulu?',
  'Aku berharap kita bisa lebih sering _____',
  'Apakah selama ini kamu merasa dicintai olehku? Sebutkan cara untuk membuatmu merasa lebih dicintai?',
  'Sebutkan topik sensitif yang penting tapi jarang kita bahas? Mengapa?',
  'Apakah mantan pasangan bisa tetap berteman baik? Mengapa?',
  'Menunggu kapan waktunya merelakan atau terus berjuang?',
  'Pilih satu, selingkuh, menjadi selingkuhan, atau diselingkuhi.',
  'Tanpa ada rasa dendam, apa yang ingin kamu sampaikan kepada mantan pasanganmu?',
  'Ceritakan patah hati terburukmu dalam satu kalimat',
  'Apa larangan dari pasanganmu yang paling tidak kamu setujui? Mengapa?',
  'Jika saat ini kamu masih menjalin hubungan dengan mantan pasanganmu, masalah apa yang akan kamu hadapi di masa mendatang?',
  'Menurutmu, apakah cinta sejati datang dengan mudah atau perlu diperjuangkan? Mengapa?',
  'Kalau tiba-tiba kamu harus LDR dengan pasanganmu, kamu memilih tetap melanjutkan hubungan atau putus? Mengapa?',
  'Jika di masa depan, pasanganmu meminta kamu meninggalkan karirmu, Apa yang akan kamu lakukan?',
  'Apa hal yang harus ada dari pasangan kamu?',
  'Hal apa yang amat kamu sukai dan tidak kamu sukai dari pasanganmu?',
  'Ada gak hal yang kamu pelajari dari keluargamu yang berpengaruh ke hubungan kita?',
  'Apa hal yang bikin kamu ilfeel dari aku dan berpengaruh ke hubungan kita?',
  'Kalau hari ini adalah hari terakhir kita bersama, apa yang ingin kamu sampaikan?',
  'Kalau diberi kesempatan memulai dari awal, hal apa yang ingin kamu ubah dari hubungan kita?',
  'Bagaimana kamu menyikapi perbedaan diantara kita?',
  'Apa yang tidak akan kamu lakukan untuk pasanganmu?',
  'Ketika situasi apa kamu merasa khawatir tentang pasanganmu?',
  'Apa yang kamu takuti dari hubungan kita?',
  'Apa yang kamu harapkan pasanganmu lakukan ketika kamu merasa gagal/sedih?',
  'Apa hal terbaik yang pernah kamu dapatkan dari pasanganmu saat ini?',
  'Apa pelajaran terbesar yang kamu pelajari dari hubungan kita selama ini?',
  'Pernahkah kamu berpikir untuk mengakhiri hubungan kita? Ceritakan',
  'Mana yang lebih penting, menerima atau memaafkan?',
  'Sebutkan sebuah momen yang membuatmu tertarik pertama kali pada pasanganmu?',
  'Dari skala 1-10, seberapa kompak kamu dan pasangan mu? Mengapa?',
  'Apakah mengakhiri suatu hubungan adalah sebuah pilihan?',
  'Kapan kamu merasa diapresiasi oleh pasanganmu?',
  'Bagaimana kesan pertama teman teman dan keluargamu tentang pasanganmu? Bagaimana pandangan mereka sekarang?',
  'Jika kamu sudah ada janji kencan dengan pasanganmu namun teman teman mu mengajakmu pergi, Apa yang akan kamu lakukan?',
  'Adakah seseorang yang lebih mengenalmu daripada pasanganmu? Siapa?',
  'Apa arti cemburu untukmu?',
  'Sebutkan satu hal yang paling romantis yang pernah pasanganmu lakukan untukmu? Jelaskan?',
  'Sebutkan kelemahan pasanganmu yang bisa kamu terima? Jelaskan?',
  'Kamu bangga menjadi pasanganku karena _____',
  'Jika kamu bisa menghilangkan satu kebiasaan dari pasanganmu, kamu akan menghilangkan _____',
  'Apa ekspektasimu terhadap pasanganmu yang belum terpenuhi saat ini? Jelaskan?',
  'Aku sedih saat melihatmu _____',
  'Sebutkan candaan di hubungan kita yang menurutmu tidak lucu?',
  'Apakah kamu dapat membayangkan pasanganmu sebagai suami/istri? Mengapa?',
  'Apakah menurutmu pasanganmu berhak mengetahui berapa penghasilanmu?',
  'Ceritakan hal yang kamu pelajari dari setiap mantan pasanganmu',
  'Kalau kamu kecewa sama pasanganmu bagaimana caranya biar kamu bisa maafin pasanganmu?',
  'Kalau kamu lagi marah karena pasanganmu, kamu mau pasanganmu melakukan apa?',
  'Apa yang bikin kamu yakin buat ngejalanin hubungan sama pasanganmu sekarang?',
  'Momen apa yang pernah kita lakuin bersama dan pengen banget kamu ulangi?',
  'Kamu mau pasanganmu jadi orang yang seperti apa buat kamu?',
  'Apakah menurutmu menonton pornografi adalah bentuk perselingkuhan? Kenapa?',
];

function newQuote() {
  var randomNumber = Math.floor(Math.random() * quotes.length);
  document.getElementById('quote').innerHTML = quotes[randomNumber];
}

newQuote();
